<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10.9 setup script
 * Date: Sat, 11 Apr 2015 23:59:56 +0300
 */

/* Servers configuration */
$i = 0;

/* Server: local server [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'local server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['nopassword'] = true;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Servers'][$i]['extension'] = 'mysqli';
/* End of servers configuration */

$cfg['blowfish_secret'] = '55297d461d7cd3.66870807';
$cfg['DefaultLang'] = 'ru';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['CheckConfigurationPermissions'] = false;
?>