CREATE TABLE IF NOT EXISTS `meetings_wishlist` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SENDER_ID` INT(18) NULL,
  `RECEIVER_ID` INT(18) NULL,
  `CREATED_AT` DATETIME NULL,
  `REASON` ENUM('rejected', 'timeout', 'selected') NOT NULL
  `EXHIBITION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `meetings_settings` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CODE` VARCHAR(45) NOT NULL,
  `IS_LOCKED` TINYINT(1) NOT NULL DEFAULT 0,
  `ACTIVE` TINYINT(1) NOT NULL DEFAULT 0,
  `GUESTS_GROUP` INT(11) NULL,
  `MEMBERS_GROUP` INT(11) NULL,
  `ADMINS_GROUP` INT(11) NULL,
  `EVENT_REJECT` VARCHAR(255) NOT NULL,
  `EVENT_SENT` VARCHAR(255) NOT NULL,
  `EVENT_TIMEOUT` VARCHAR(255) NOT NULL,
  `REPR_PROP_ID` INT(11) NOT NULL,
  `REPR_PROP_CODE` VARCHAR(255) NOT NULL,
  `TIMEOUT_VALUE` INT(5) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `meetings_timeslots` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EXHIBITION_ID` INT NOT NULL,
  `SORT` INT(3) NOT NULL DEFAULT 10,
  `NAME` VARCHAR(45) NOT NULL,
  `TIME_FROM` INT UNSIGNED NOT NULL,
  `TIME_TO` INT UNSIGNED NOT NULL,
  `SLOT_TYPE` ENUM('meet','coffee') NOT NULL DEFAULT 'meet',
  PRIMARY KEY (`ID`),
  INDEX `EXHIBITIONS_IDX_idx` (`EXHIBITION_ID` ASC),
  CONSTRAINT `exhibition`
    FOREIGN KEY (`EXHIBITION_ID`)
    REFERENCES `meetings_settings` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `meetings_requests` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SENDER_ID` INT(18) NOT NULL,
  `RECEIVER_ID` INT(18) NOT NULL,
  `CREATED_AT` DATETIME NULL,
  `UPDATED_AT` DATETIME NULL,
  `MODIFIED_BY` INT(18) NULL,
  `TIMESLOT_ID` INT(18) NOT NULL,
  `STATUS` ENUM('process', 'confirmed', 'rejected', 'timeout') NOT NULL DEFAULT 'process',
  `EXHIBITION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;
